name: figma_to_flutter
version: 0.1.0
authors:
- Aloïs Deniel <alois.deniel@outlook.com>
description: a tool for generating Flutter widgets from Figma components.
dependencies:
  http:
  vector_math:
  yaml:
  recase:
  source_gen: 0.8.3
  code_builder: 3.1.1 